// npm+angular/src/app/app.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  type ElementRef,
  ViewChild,
  type AfterViewInit,
} from "@angular/core";
import "@tiro-health/web-sdk";
import { SDCClient } from "@tiro-health/web-sdk";

const BACKEND_URL = "https://sdc.tiro.health/fhir/r5";
const DATA_SERVER_URL =
  "https://fhir-candle-35032072625.europe-west1.run.app/fhir/r4";

@Component({
  selector: "app-root",
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent implements AfterViewInit {
  @ViewChild("formFiller", { static: true })
  formFillerRef!: ElementRef<HTMLElement>;

  @ViewChild("magicClipboard", { static: true })
  magicClipboardRef!: ElementRef<HTMLElement>;

  private sdcClient = new SDCClient({
    baseUrl: BACKEND_URL,
    dataEndpoint: DATA_SERVER_URL,
    auth: () => getAccessToken(),
  });

  ngAfterViewInit(): void {
    const formFiller = this.formFillerRef.nativeElement as HTMLElement & {
      sdcClient: SDCClient;
    };
    const clipboard = this.magicClipboardRef.nativeElement;

    // Set SDCClient with auth on the form filler
    formFiller.sdcClient = this.sdcClient;

    // Form filler events
    formFiller.addEventListener("tiro-ready", (event: Event) => {
      console.log(
        "tiro-ready: Questionnaire loaded",
        (event as CustomEvent).detail.questionnaire,
      );
    });

    formFiller.addEventListener("tiro-submit", (event: Event) => {
      console.log(
        "tiro-submit: Form submitted",
        (event as CustomEvent).detail.response,
      );
    });

    formFiller.addEventListener("tiro-update", (event: Event) => {
      console.log(
        "tiro-update: Form values changed",
        (event as CustomEvent).detail.response,
      );
    });

    formFiller.addEventListener("tiro-error", (event: Event) => {
      console.error("tiro-error:", (event as CustomEvent).detail.error);
    });

    formFiller.addEventListener("tiro-validate", (event: Event) => {
      const detail = (event as CustomEvent).detail;
      console.log("tiro-validate:", detail.isValid, detail.operationOutcome);
    });

    // Magic clipboard events
    clipboard.addEventListener("tiro-populate-start", (event: Event) => {
      const detail = (event as CustomEvent).detail;
      console.log(
        "tiro-populate-start: Notes:",
        detail.notes?.length || 0,
        "chars, Files:",
        detail.files?.length || 0,
      );
    });

    clipboard.addEventListener("tiro-populate-complete", (event: Event) => {
      console.log(
        "tiro-populate-complete:",
        (event as CustomEvent).detail.response,
      );
    });

    clipboard.addEventListener("tiro-populate-error", (event: Event) => {
      console.error(
        "tiro-populate-error:",
        (event as CustomEvent).detail.error,
      );
    });
  }
}

/**
 * Replace this with your actual access token retrieval logic.
 * For example, fetch from your auth provider or session storage.
 */
function getAccessToken(): string {
  return "your-access-token";
}

<div class="container">
  <div class="app-code-section">
    <h1 class="title">
      Tiro Web SDK Demo
      <span class="app-code-badge">Your App</span>
    </h1>
  </div>
  <main class="main-content">
    <div class="sdk-component-wrapper">
      <span class="sdk-component-badge">SDK: PatientSelector</span>
      <tiro-patient-selector
        for="form-filler"
        [attr.data-endpoint-address]="dataUrl">
      </tiro-patient-selector>
    </div>
    <div class="sdk-component-wrapper">
      <span class="sdk-component-badge">SDK: FormFiller</span>
      <tiro-form-filler
        #formFiller
        id="form-filler"
        [attr.questionnaire]="questionnaireUrl"
        [attr.sdc-endpoint-address]="sdcUrl">
      </tiro-form-filler>
    </div>
    <div class="sdk-component-wrapper">
      <span class="sdk-component-badge">SDK: Narrative</span>
      <tiro-narrative for="form-filler"></tiro-narrative>
    </div>
  </main>

  <div class="sdk-legend">
    <h3>Component Legend</h3>
    <div class="legend-item">
      <div class="legend-box sdk"></div>
      <span class="legend-label">SDK Component</span>
    </div>
    <div class="legend-item">
      <div class="legend-box app"></div>
      <span class="legend-label">Your Application</span>
    </div>
  </div>
</div>

// npm+react/src/App.tsx
import { useEffect, useRef } from "react";
import "@tiro-health/web-sdk";
import { SDCClient } from "@tiro-health/web-sdk";
import "./App.css";

const QUESTIONNAIRE_URI =
  "http://templates.tiro.health/templates/example|1.0.0";
const BACKEND_URL = "https://sdc.tiro.health/fhir/r5";
const DATA_SERVER_URL =
  "https://fhir-candle-35032072625.europe-west1.run.app/fhir/r4";

/**
 * Replace this with your actual access token retrieval logic.
 * For example, fetch from your auth provider or session storage.
 */
function getAccessToken(): string {
  return "your-access-token";
}

const sdcClient = new SDCClient({
  baseUrl: BACKEND_URL,
  dataEndpoint: DATA_SERVER_URL,
  auth: () => getAccessToken(),
});

function App() {
  const formFillerRef = useRef<HTMLElement>(null);
  const magicClipboardRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const formFiller = formFillerRef.current;
    const clipboard = magicClipboardRef.current;
    if (!formFiller) return;

    // Set SDCClient with auth on the form filler
    (formFiller as HTMLElement & { sdcClient: SDCClient }).sdcClient =
      sdcClient;

    // Form filler events
    formFiller.addEventListener("tiro-ready", (event: Event) => {
      console.log(
        "tiro-ready: Questionnaire loaded",
        (event as CustomEvent).detail.questionnaire
      );
    });

    formFiller.addEventListener("tiro-submit", (event: Event) => {
      console.log(
        "tiro-submit: Form submitted",
        (event as CustomEvent).detail.response
      );
    });

    formFiller.addEventListener("tiro-update", (event: Event) => {
      console.log(
        "tiro-update: Form values changed",
        (event as CustomEvent).detail.response
      );
    });

    formFiller.addEventListener("tiro-error", (event: Event) => {
      console.error("tiro-error:", (event as CustomEvent).detail.error);
    });

    formFiller.addEventListener("tiro-validate", (event: Event) => {
      const detail = (event as CustomEvent).detail;
      console.log("tiro-validate:", detail.isValid, detail.operationOutcome);
    });

    // Magic clipboard events
    if (clipboard) {
      clipboard.addEventListener("tiro-populate-start", (event: Event) => {
        const detail = (event as CustomEvent).detail;
        console.log(
          "tiro-populate-start: Notes:",
          detail.notes?.length || 0,
          "chars, Files:",
          detail.files?.length || 0
        );
      });

      clipboard.addEventListener("tiro-populate-complete", (event: Event) => {
        console.log(
          "tiro-populate-complete:",
          (event as CustomEvent).detail.response
        );
      });

      clipboard.addEventListener("tiro-populate-error", (event: Event) => {
        console.error(
          "tiro-populate-error:",
          (event as CustomEvent).detail.error
        );
      });
    }
  }, []);

  return (
    <div className="container">
      <h1 className="title">Tiro Web SDK Demo</h1>
      <main>
        <div className="section-header">
          <span className="section-title">Magic Clipboard</span>
          <span className="beta-badge">Beta</span>
        </div>
        <tiro-magic-clipboard
          ref={magicClipboardRef}
          for="form-filler"
        />
        <div className="section-header">
          <span className="section-title">Form Filler</span>
          <span className="ga-badge">GA</span>
        </div>
        <tiro-form-filler
          ref={formFillerRef}
          id="form-filler"
          questionnaire={QUESTIONNAIRE_URI}
          sdc-endpoint-address={BACKEND_URL}
          data-endpoint-address={DATA_SERVER_URL}
        />
        <div className="section-header">
          <span className="section-title">Narrative</span>
          <span className="ga-badge">GA</span>
        </div>
        <tiro-narrative for="form-filler" />
      </main>
    </div>
  );
}

export default App;
